apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-db-deployment
  labels:
    app: quote
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: quote-db-pod
  template:
    metadata:
      labels:
        pod: quote-db-pod
    spec:
      containers:
        - name: quote-db-service
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: quote-secret
                  key: passw
            - name: POSGRES_USER
              valueFrom:
                secretKeyRef:
                  name: quote-secret
                  key: usr
            - name: POSTGRES_DB
              value: optimization-db
---
apiVersion: v1
kind: Service
metadata:
  name: quote-db-service
spec:
  selector:
    app: quote
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432